# Generated by Django 6.0.3 on 2026-03-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='materials/excel/')),
                ('excel_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('powerpoint_file', models.FileField(blank=True, null=True, upload_to='materials/powerpoint/')),
                ('powerpoint_link', models.URLField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='materials/pdf/')),
                ('pdf_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Material',
                'verbose_name_plural': 'Project Materials',
            },
        ),
    ]
