# Generated by Django 6.0.3 on 2026-03-10 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Route Number')),
                ('name', models.CharField(max_length=200, verbose_name='Route Name')),
                ('route_type', models.CharField(choices=[('bus', 'Bus'), ('minibus', 'Minibus'), ('express', 'Express'), ('night', 'Night Bus')], default='bus', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('color', models.CharField(default='#0ea5e9', max_length=7, verbose_name='Color (hex)')),
                ('frequency_minutes', models.PositiveIntegerField(default=15, verbose_name='Frequency (min)')),
                ('operating_hours', models.CharField(default='06:00 - 23:00', max_length=50, verbose_name='Operating Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Stop Name')),
                ('name_az', models.CharField(blank=True, max_length=200, verbose_name='Name (Azerbaijani)')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Stop Code')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('has_shelter', models.BooleanField(default=False, verbose_name='Has Shelter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Plate Number')),
                ('vehicle_type', models.CharField(default='bus', max_length=50, verbose_name='Vehicle Type')),
                ('capacity', models.PositiveIntegerField(default=80, verbose_name='Capacity')),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('maintenance', 'Maintenance'), ('offline', 'Offline')], default='active', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='transport.route', verbose_name='Route')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('speed', models.FloatField(default=0.0, verbose_name='Speed (km/h)')),
                ('heading', models.FloatField(default=0.0, verbose_name='Heading (degrees)')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='transport.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Location',
                'verbose_name_plural': 'Vehicle Locations',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_routes', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='transport.route')),
            ],
            options={
                'verbose_name': 'Favorite Route',
                'verbose_name_plural': 'Favorite Routes',
                'unique_together': {('user', 'route')},
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('distance_from_previous', models.PositiveIntegerField(default=0, verbose_name='Distance from prev. (m)')),
                ('travel_time_from_previous', models.PositiveIntegerField(default=0, verbose_name='Travel time from prev. (min)')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='transport.route', verbose_name='Route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='transport.stop', verbose_name='Stop')),
            ],
            options={
                'verbose_name': 'Route Stop',
                'verbose_name_plural': 'Route Stops',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order'), ('route', 'stop')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stops', to=settings.AUTH_USER_MODEL)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='transport.stop')),
            ],
            options={
                'verbose_name': 'Favorite Stop',
                'verbose_name_plural': 'Favorite Stops',
                'unique_together': {('user', 'stop')},
            },
        ),
    ]
